name: Deploy

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: pip install -r ./requirements.txt
    - name: Update index
      run: python scripts/gen_index.py
    - name: Commit changes
      id: asset-auto-commit-action
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: "Update Index Json"